name: Flutter tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15.x'
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '1.22.5'
    - name: Run flutter tests
      run: flutter test
      working-directory: ./social_good
